module.exports = {
  COLLECTIONS_RECEIVED: "COLLECTIONS_RECEIVED",
  SINGLE_COLLECTION_RECEIVED: "SINGLE_COLLECTION_RECEIVED",
  COLLECTION_CREATED: "COLLECTION_CREATED",
  COLLECTION_UPDATED: "COLLECTION_UPDATED",
  COLLECTION_DELETED: "COLLECTION_DELETED"
};
