var SavedArticleConstants = {
  SAVED_ARTICLES_RECEIVED: "SAVED_ARTICLES_RECEIVED",
  ARTICLE_RECEIVED: "ARTICLE_RECEIVED",
  ARTICLE_CREATED: "ARTICLE_CREATED",
  ARTICLE_DESTROYED: "ARTICLE_DESTROYED"

};

module.exports = SavedArticleConstants;
