# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4fd8737a54c09a7592886e90bb72f7bce86394f983ee0efc511a44796ca8537e2463557d9d6727a35a9d807a2fe37312309440277c5fa2b6fb50b3beb88905e2

test:
  secret_key_base: 87d4aada4eaec1a46d65b874bdf7b6641d0bf0733c63ecc12d1c45fcb669bbf80886dac0f755ed75b12a9bb87665811632d8990b869fae7d51212a4f699fbde1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
